/***************************************************************************************************************
 * Created By :
 * 
 * 
 * ************************************************************************************************************/
public class DemoArithmaticOperatorClass{
    //This method for addition
    public static Integer addTwoNumber(Integer val1, Integer val2){
        return val1+val2;
	}
    //This method for multiplication
    public static Integer multiplyTwoNumber(Integer val1, Integer val2){
        return val1*val2;
	}
    //This method for substraction
    public Integer subTwoNumber(Integer val1, Integer val2){
        return val1-val2;
	}
}