/**********************************************************************************************************************************
 * @Created By: Aashish Ranjan
 * @Created Dtae: 20-11-2018
 * @Class Name:Helper_CaseMail
 * @Description: Helper class for CaseMail Trigger.
 * *******************************************************************************************************************************/
public class Helper_CaseMail {
    public static void sendMail(List<Case> caseList){
        
        for(Case c :caseList){
            //if(c.)
        }
    }

}